[package]
name = "argon2"
version = "0.1.0"

[lib]
name = "argon2"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.24.0"
argon2 = "0.3.4"
rand_core = { version = "0.6", features = ["std"] }
