[package]
name = "argon2"
version = "0.2.0"

[lib]
crate-type = ["dylib"]
name = "argon2"
path = "src/lib.rs"

[dependencies]
argon2 = "0.5"
rand_core = { version = "0.6", features = ["std"] }
rustler = "0.32"
